- name: Install Apache and PHP
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ 'httpd' if ansible_os_family == 'RedHat' else 'apache2' }}"
    - php
    - php-mysql

- name: Start and enable Apache
  ansible.builtin.service:
    name: "{{ 'httpd' if ansible_os_family == 'RedHat' else 'apache2' }}"
    state: started
    enabled: true

- name: Download WordPress
  ansible.builtin.get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: Extract WordPress
  ansible.builtin.unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/html/
    remote_src: true
    extra_opts: [--strip-components=1]

- name: Remove default Apache index.html
  ansible.builtin.file:
    path: /var/www/html/index.html
    state: absent

- name: Configure wp-config.php
  ansible.builtin.template:
    src: wp-config.php.j2
    dest: /var/www/html/wp-config.php
    owner: "{{ 'apache' if ansible_os_family == 'RedHat' else 'www-data' }}"
    group: "{{ 'apache' if ansible_os_family == 'RedHat' else 'www-data' }}"
    mode: '0644'

- name: Set permissions for WordPress
  ansible.builtin.file:
    path: /var/www/html
    owner: "{{ 'apache' if ansible_os_family == 'RedHat' else 'www-data' }}"
    group: "{{ 'apache' if ansible_os_family == 'RedHat' else 'www-data' }}"
    recurse: yes

- name: Restart Apache
  ansible.builtin.service:
    name: "{{ 'httpd' if ansible_os_family == 'RedHat' else 'apache2' }}"
    state: restarted
