global:
  slack_api_url: 'https://hooks.slack.com/services/T01C9T2TAJZ/B049ZB1PLJ1/XC8gmr'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#docker-test'