apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: demo
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          # image: demo-backend:latest
          image: ghcr.io/t1mxn1n/demo-backend:latest
          # imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_USER
              value: postgres
            - name: DB_PASS
              value: postgres
            - name: DB_NAME
              value: demo
      imagePullSecrets:
          - name: ghcr-creds
