Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  # Dev VM
  config.vm.define "dev" do |dev|
    dev.vm.hostname = "dev"
    dev.vm.network "private_network", ip: "192.168.56.10"
  end

  # Prod VM
  config.vm.define "prod" do |prod|
    prod.vm.hostname = "prod"
    prod.vm.network "private_network", ip: "192.168.56.11"
  end
end
