networks:
  monitoring:
    driver: bridge

services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - monitoring

  ui:
    image: ghcr.io/codeby-devops/ui:bug
    environment:
      - POST_SERVICE_HOST=post
      - POST_SERVICE_PORT=5000
      - COMMENT_SERVICE_HOST=comment
      - COMMENT_SERVICE_PORT=9292
    ports:
      - 9292:9292/tcp
    depends_on:
      - comment
      - post
    networks:
      - monitoring

  comment:
    image: ghcr.io/codeby-devops/comment:bug
    environment:
      - COMMENT_DATABASE_HOST=post_db
      - COMMENT_DATABASE=comments
    depends_on:
      - post_db
    networks:
      - monitoring

  post:
    image: ghcr.io/codeby-devops/post:bug
    environment:
      - POST_DATABASE_HOST=post_db
      - POST_DATABASE=posts
    depends_on:
      - post_db
    ports:
      - "5000:5000"
    networks:
      - monitoring

volumes:
  post_db:
