# Базовый образ
FROM alpine:latest

RUN apk update && apk add --no-cache nginx bash

RUN mkdir -p /opt/www

COPY index_a.html /opt/www/index.html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
