FROM node:22.14.0 AS builder

RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*

WORKDIR /app


RUN git clone https://github.com/irevenko/web-chat.git /app

RUN npm install

FROM node:22.14.0-alpine

WORKDIR /app

COPY --from=builder /app /app

EXPOSE 3000

CMD ["npm", "start"]
