# Базовый образ
FROM debian:11

RUN apt-get update && apt-get install -y nginx && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /opt/www

COPY index_d.html /opt/www/index.html
COPY nginx.conf /etc/nginx/sites-available/default

EXPOSE 80

ENTRYPOINT ["nginx", "-g", "daemon off;"]
