apiVersion: batch/v1
kind: Job
metadata:
  name: init-db
  namespace: demo
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: init-db
          image: postgres:15
          command:
            - sh
            - -c
            - |
              echo "⏳ Waiting for PostgreSQL to be ready...";
              until pg_isready -h postgres -U postgres; do sleep 2; done;
              echo "initializing schema...";
              psql -v ON_ERROR_STOP=1 -h postgres -U postgres -d demo <<-EOSQL
                CREATE TABLE IF NOT EXISTS items (
                  id SERIAL PRIMARY KEY,
                  name TEXT NOT NULL
                );
              EOSQL
          env:
            - name: PGPASSWORD
              value: postgres