---
- name: Setup web server
  hosts: web
  become: yes
  vars:
    env_name: "{{ lookup('env', 'ANSIBLE_ENV') | default('dev', true) }}"
  tasks:
    - name: Install required packages
      apt:
        name:
          - wget
          - htop
          - nginx
        state: present
        update_cache: yes

    - name: Ensure nginx is running
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Show environment info
      debug:
        msg: "This host is in {{ env_name }} environment"
...