version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: wp-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - backend

  app:
    image: wordpress:latest
    container_name: wp-app
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wp_data:/var/www/html
    networks:
      - backend
      - frontend

  proxy:
    image: nginx:latest
    container_name: wp-proxy
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - frontend

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
