apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: demo
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
    scrape_configs:
      - job_name: 'node-exporter'
        static_configs:
          - targets: ['node-exporter.demo.svc.cluster.local:9100']
